// NEON BASTION string table [zh-HK, en] (cyber-kit i18n, shared localStorage 'cyber.lang')
import { i18n } from 'cyber-kit';
i18n.add({
  'doc.title': ['霓虹堡壘 NEON BASTION · 3D 塔防', 'NEON BASTION · 3D tower defense'],
  title: ['霓虹堡壘', 'NEON BASTION'], titleEn: ['NEON BASTION', '霓虹堡壘'], subtitle: ['賽博塔防 · 無盡波數', 'CYBER TOWER DEFENSE · ENDLESS WAVES'],
  tagline: ['病毒同無人機沿住數據通道衝向核心。<br>點擊發光格子起塔，點擊塔升級或出售。8 張香港地圖，再加永不完結嘅無盡模式！', 'Viruses and drones stream down the data path toward the core.<br>Tap a glowing pad to build, tap a tower to upgrade or sell. 8 Hong Kong maps plus an endless mode that never ends!'],
  campaign: ['戰役', 'CAMPAIGN'], campaignS: ['8 張地圖 · 星級評分', '8 MAPS · STAR RATINGS'], endless: ['無盡模式', 'ENDLESS'], endlessS: ['波數無限 · 衝最高分', 'NO FINAL WAVE · HIGH SCORE'],
  best: ['最高分', 'BEST'], bestWave: ['最遠波數', 'BEST WAVE'], starsTotal: ['星數', 'STARS'],
  touchHint: ['點格子起塔 · 點塔升級／出售 · 單手玩', 'Tap a pad to build · tap a tower to upgrade / sell · one thumb'],
  keysHint: ['<b>空白鍵</b> 召喚下一波　<b>F</b> 加速　<b>P</b> 暫停　<b>M</b> 靜音', '<b>SPACE</b> next wave　<b>F</b> speed　<b>P</b> pause　<b>M</b> mute'],
  mapsTitle: ['揀地圖', 'SELECT MAP'], mapsSub: ['完成一張地圖解鎖下一張', 'Clear a map to unlock the next'], back: ['返回', 'BACK'],
  wavesN: ['{n} 波', '{n} WAVES'], locked: ['未解鎖', 'LOCKED'], trialLock: ['金級解鎖', 'GOLD UNLOCK'],
  core: ['核心', 'CORE'], credits: ['資金', 'CREDITS'], wave: ['波數', 'WAVE'], score: ['分數', 'SCORE'],
  startWave: ['開始第 {n} 波', 'START WAVE {n}'], startWaveS: ['召喚病毒', 'SEND THE SWARM'],
  nextIn: ['下一波 {s} 秒', 'NEXT WAVE {s}s'], callEarly: ['提早召喚 +{b}', 'CALL EARLY +{b}'], callEarlyS: ['獎勵資金', 'BONUS CREDITS'],
  waveRunning: ['第 {n} 波進行中', 'WAVE {n} IN PROGRESS'], waveRunningS: ['清晒先到下一波', 'CLEAR THE FIELD'],
  speedTip: ['速度 1× / 2× (F)', 'Speed 1× / 2× (F)'], pauseTip: ['暫停 (P / Esc)', 'Pause (P / Esc)'], muteTip: ['靜音 (M)', 'Mute (M)'],
  waveN: ['第 {n} 波', 'WAVE {n}'], finalWave: ['最後一波', 'FINAL WAVE'], bossIncoming: ['巨型病毒來襲', 'MEGA VIRUS INBOUND'], warning: ['警告', 'WARNING'],
  cleared: ['清場 +{bonus} · 利息 +{i}', 'CLEAR +{bonus} · INTEREST +{i}'],
  milestone: ['里程碑 · 第 {n} 波', 'MILESTONE · WAVE {n}'], milestoneS: ['+{pts} 分 · 核心 +3', '+{pts} PTS · CORE +3'],
  firstHint: ['點擊發光格子起塔', 'Tap a glowing pad to build'], firstHint2: ['準備好就撳「開始」', 'Press START when ready'],
  build: ['起塔', 'BUILD'], upgrade: ['升級', 'UPGRADE'], maxed: ['已滿級', 'MAX'], sell: ['出售', 'SELL'], lvl: ['Lv{n}', 'LV{n}'],
  noCredits: ['資金不足', 'Not enough credits'], cantNow: ['而家唔可以', 'Not now'],
  'tw.laser': ['激光塔', 'LASER'], 'tw.cryo': ['冷凍脈衝', 'CRYO PULSE'], 'tw.missile': ['導彈塔', 'MISSILE'], 'tw.tesla': ['電弧塔', 'TESLA'], 'tw.overclock': ['超頻節點', 'OVERCLOCK'],
  'td.laser': ['單體快速射擊 · 可打空', 'Fast single target · hits air'], 'td.cryo': ['範圍減速 · 可打空', 'Area slow · hits air'], 'td.missile': ['爆炸範圍傷害 · 只打地面', 'Splash damage · ground only'],
  'td.tesla': ['連鎖閃電 · 破盾 ×2', 'Chain lightning · ×2 vs shields'], 'td.overclock': ['附近塔加傷害同射速', 'Buffs nearby towers'],
  sDmg: ['傷害', 'DMG'], sRange: ['射程', 'RNG'], sRate: ['射速', 'RATE'], sSlow: ['減速', 'SLOW'], sChain: ['連鎖', 'CHAIN'], sBuff: ['加成', 'BUFF'], sKills: ['擊殺', 'KILLS'],
  'en.runner': ['疾行病毒', 'RUNNER'], 'en.tank': ['裝甲病毒', 'ARMORED TANK'], 'en.shield': ['護盾病毒', 'SHIELDED'], 'en.splitter': ['分裂病毒', 'SPLITTER'], 'en.drone': ['無人機', 'DRONE'], 'en.boss': ['巨型病毒', 'MEGA VIRUS'],
  'eh.tank': ['裝甲會減低每次傷害 · 用導彈或電弧', 'Armor blocks small hits · use missiles or tesla'], 'eh.shield': ['護盾會回復 · 電弧破盾快一倍', 'Shields regenerate · tesla breaks them ×2'],
  'eh.splitter': ['死後分裂成 3 隻細病毒', 'Splits into 3 minis on death'], 'eh.drone': ['飛行唔跟路 · 導彈打唔到', 'Flies straight at the core · missiles cannot hit'],
  newEnemy: ['新敵人：{name}', 'NEW ENEMY: {name}'],
  pausedS: ['PAUSED', '已暫停'], restart: ['重新開始', 'RESTART'], quit: ['離開', 'QUIT'],
  coreLost: ['核心失守', 'CORE BREACHED'], failed: ['防線崩潰', 'DEFENSE DOWN'], overS: ['BASTION FALLEN', '防線崩潰'], kills: ['擊殺', 'KILLS'],
  revive: ['續命 · 核心 +{hp}', 'CONTINUE · CORE +{hp}'], reviveAd: ['睇廣告續命', 'WATCH AD'], reviveFree: ['免費續命（網頁版）', 'FREE ON WEB'], noReward: ['冇獎勵', 'No reward'],
  revived: ['核心修復！', 'CORE RESTORED!'], retry: ['再試', 'RETRY'],
  winKicker: ['防線守住', 'SECTOR SECURED'], winTitle: ['勝利', 'VICTORY'], winS: ['SECTOR SECURED', '防線守住'], next: ['下一張地圖', 'NEXT MAP'], allClear: ['全部 8 張地圖完成！試吓無盡模式', 'All 8 maps cleared! Try endless mode'],
  hpLeft: ['剩餘核心', 'CORE LEFT'], time: ['時間', 'TIME'],
  trialTitle: ['試玩完結', 'TRIAL ENDS HERE'], trialEndless: ['試玩版無盡模式玩到第 {n} 波。喺 CYBER ARCADE 解鎖金級，就可以無限玩落去（包括日後加入金級嘅新遊戲）。', 'The trial runs endless mode up to wave {n}. Unlock GOLD in CYBER ARCADE to keep going (includes every future Gold game).'],
  trialMap: ['試玩版開放地圖 1–2。喺 CYBER ARCADE 解鎖金級，就可以玩晒 8 張地圖同無盡模式。', 'The trial includes maps 1–2. Unlock GOLD in CYBER ARCADE for all 8 maps and full endless mode.'],
  unlock: ['解鎖金級', 'UNLOCK GOLD'], unlockS: ['返去 CYBER ARCADE', 'BACK TO CYBER ARCADE'], trialNote: ['試玩中 · 今日仲有 {n} 次', 'TRIAL · {n} LEFT TODAY'], trialNoteBare: ['試玩中', 'TRIAL'],
  noHub: ['請喺 CYBER ARCADE App 解鎖', 'Unlock in the CYBER ARCADE app'],
  speed2: ['2× 加速', '2× SPEED'], speed1: ['1× 正常', '1× SPEED'],
  fatal: ['載入失敗', 'Failed to start'],
});
